### ISSUE TITLE
Templating probe address

### ISSUE THREAD

**Issue by fireflycons** [yeahdongcn/kustohelmize#18]
Given
```yaml
          args: 
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          livenessProbe: 
            httpGet: 
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
```

how would I generate this output

```yaml
          args: 
            - --health-probe-bind-address=:{{ .Values.mydeployment.manager.probePort }}
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          livenessProbe: 
            httpGet: 
              path: /healthz
              port: {{ .Values.mydeployment.manager.probePort }}
            initialDelaySeconds: 15
            periodSeconds: 20
````

I can see how to set the port in `livenessProbe`, but how to adjust the argument when only part of the argument value is to be templated?

**Comment by yeahdongcn** [comment]
It's impossible right now as the `args` is a list of strings and I didn't parse them into a map...

Here is how I set args in my project:

```yaml
- strategy: control-if-yaml
  key: controller.args
  value:
    - --log-level={{ .Values.policy.controller.logLevel }}
    - --refresh-period=5s
```
