### ISSUE TITLE
Issue with rendering chained strategies

### ISSUE THREAD

**Issue by fireflycons** [yeahdongcn/kustohelmize#20]
Fileconfig
```yaml
    spec.template.spec.containers[1].image:
    - strategy: inline
      key: manager.image.repository
      value: myrepo/myoperator
    - strategy: inline
      key: myoperator.imageTag  # <- Defined in a .tpl file
```

Expected output
```yaml
   image: "{{ .Values.myOperatorControllerManagerDeployment.manager.image.repository }}:{{ include "myoperator.imageTag" . }}"
```
Actual output
```yaml
   image: "{{ .Values.myOperatorControllerManagerDeployment.manager.image.repository }}:{{ myoperator.imageTag }}"
```
