### ISSUE TITLE
control-if fields without values generate {} in values.yaml

### ISSUE THREAD

**Issue by yeahdongcn** [yeahdongcn/kustohelmize#27]
By using the latest commit of kustohelmize, for `control-if` fields without values, `{}` is injected in generated values.yaml. 

@fireflycons could you please take a look? Thanks.

```
    spec.validator.toolkit.env:
    - strategy: control-if
      key: validator.toolkit.env
    spec.validator.driver.env:
    - strategy: control-if
      key: validator.driver.env
```

Looks like this is introduced by https://github.com/yeahdongcn/kustohelmize/commit/6ba47091c9d0a468169ac6e576248036ab419dcd

```diff
   validator:
-    containerToolkit: {}
-    driver: {}
+    args: {}
+    toolkit:
+      env: {}
+    driver:
+      env: {}
+    env: {}
     image: validator
     imagePullPolicy: Always
+    imagePullSecrets: {}
     repository: harbor.vmware.com
+    resources: {}
     version: 1.1.0
```
