### ISSUE TITLE
Patch value even if key is not present

### ISSUE THREAD

**Issue by PierrePIRONIN** [yeahdongcn/kustohelmize#33]
## Issue
Currently it seems not possible to patch a value in the `config` file if the key is not present in the original manifest.  
Would be nice to permit it.

## Simple example
_my-pod.yaml_
```
apiVersion: apps/v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: my-image
      name: my-container
  ```
  _my-chart.config_
```
logger: {}

chartname: my-chart

sharedValues:
  securityContext:
    runAsNonRoot: false
    runAsUser: 1000

globalConfig: {}

fileConfig:
  charts/my-chart/my-pod.yaml: {
    spec.containers[0].securityContext:
    - strategy: newline-yaml
      key: sharedValues.securityContext
  }
```

SecurityContext is not added to Pod after generation.
