### ISSUE TITLE
Have a way to add items into array

### ISSUE THREAD

**Issue by PierrePIRONIN** [yeahdongcn/kustohelmize#38]
## Issue

Would be nice to have a solution to add a code block with strategy in an array.

## Example
Given this snippet
```
spec:
  template:
    spec:
      containers:
      - volumeMounts:             
        - mountPath: /opt/metal3/certs/ca
          name: cacert
          readOnly: true
        - mountPath: /opt/metal3/auth/ironic
          name: ironic-credentials
          readOnly: true
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
```
and having a strategy like
```
spec.template.spec.containers[0].volumeMounts[3]:
- strategy: control-with
  key: sharedValues.extraVolumeMounts
```
should results to
```
spec:
  template:
    spec:
      containers:
      - volumeMounts:             
        - mountPath: /opt/metal3/certs/ca
          name: cacert
          readOnly: true
        - mountPath: /opt/metal3/auth/ironic
          name: ironic-credentials
          readOnly: true
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- with .Values.extraVolumeMounts }}
        {{- . | toYaml | nindent 10 }}
        {{- end }}
```
