### ISSUE TITLE
[Feature Request] Support multiple strategies on xpath

### ISSUE THREAD

**Issue by yeahdongcn** [yeahdongcn/kustohelmize#49]
For example, given 
```
spec.template.spec.containers[0].ports[2]:
- strategy: append-with
  key: sharedValues.extraPorts
- strategy: control-if
  conditions:
  - key: "!sharedValues.webhook.disabled"
  - key: sharedValues.tls.enabled
  conditionOperator: and
```

I would want
```
{{- if and (not .Values.webhook.disabled) .Values.tls.enabled }}
- containerPort: 9443
  name: webhook-server
  protocol: TCP
{{- with .Values.extraPorts }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
```

but it results to
```
- containerPort: 9443
  name: webhook-server
  protocol: TCP
{{- with .Values.extraPorts }}
{{- toYaml . | nindent 2 }}
{{- end }}
```
