### ISSUE TITLE
[Feature Request] Support nested strategies on list or map

### ISSUE THREAD

**Issue by yeahdongcn** [yeahdongcn/kustohelmize#50]
For example, given
```
    spec.template.spec.containers[1].env:
    - strategy: control-if
      conditions:
      - key: sharedValues.tls.enabled
      - key: sharedValues.mariadb.enabled
      conditionOperator: or
    spec.template.spec.containers[1].env[0]:
    - strategy: control-if
      condition: sharedValues.tls.enabled
    spec.template.spec.containers[1].env[1]:
    - strategy: control-if
      condition: sharedValues.mariadb.enabled
    spec.template.spec.containers[1].env[2]:
    - strategy: control-if
      condition: sharedValues.mariadb.enabled
```

I would want

```
          {{- if or .Values.tls.enabled .Values.mariadb.enabled }}
        env:
            {{- if .Values.tls.enabled }}
        - name: IRONIC_REVERSE_PROXY_SETUP
          value: "true"
            {{- end }}
            {{- if .Values.mariadb.enabled }}
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password
            {{- end }}
            {{- if .Values.mariadb.enabled }}
        - name: IRONIC_USE_MARIADB
          value: "true"
            {{- end }}
          {{- end }}
```

but it results to

```
          {{- if or .Values.tls.enabled .Values.mariadb.enabled }}
          env: 
          - name: IRONIC_REVERSE_PROXY_SETUP
            value: "true"
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mariadb-password
          - name: IRONIC_USE_MARIADB
            value: "true"
          {{- end }}
```
