### ISSUE TITLE
[Feature request] Add drop strategy

### ISSUE THREAD

**Issue by sathieu** [yeahdongcn/kustohelmize#51]
I want a strategy to remove a key in a map completely.

My usecase it to remove annotations `app.quarkus.io/build-timestamp` and`app.quarkus.io/quarkus-version`  from:

``` yaml
metadata:
  annotations: 
    app.quarkus.io/build-timestamp: 2025-02-18 - 15:18:03 +0000
    app.quarkus.io/quarkus-version: 3.15.3
    app.quarkus.io/vcs-uri: https://github.com/keycloak/keycloak.git
``` 

([ref](https://gitlab.com/kubitus-project/external-helm-charts/keycloak-operator/-/blob/5cf12b7c0906d326d09e8e1e50e1ace3d338d809/charts/keycloak-operator/templates/keycloak-operator-deployment.yaml#L6-9))

To have the following result:

``` diff
 metadata:
   annotations: 
-    app.quarkus.io/build-timestamp: 2025-02-18 - 15:18:03 +0000
-    app.quarkus.io/quarkus-version: 3.15.3
     app.quarkus.io/vcs-uri: https://github.com/keycloak/keycloak.git
```
