### ISSUE TITLE
There are chances that `helm lint <<chartname>>` may fail in handling slice.map

### ISSUE THREAD

**Issue by yeahdongcn** [yeahdongcn/kustohelmize#8]
This is an indent issue.

```
    spec: 
      terminationGracePeriodSeconds: 10
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:         
        -           image: "{{ .Values.mtControllerManagerDeployment.manager.image.repository }}:{{ .Values.mtControllerManagerDeployment.manager.image.tag }}" <<=====
readinessProbe: <<=====
            httpGet: 
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
```
